// AUTO-GENERATED by scripts/generate-mock.mjs — do not edit by hand.
// Source: public Steam store API. Media is served from Steam's CDN.
// This is the offline fallback catalogue: the site renders fully without a RAWG key.
import type { Game } from '@/types/game'

export const MOCK_GAMES: Game[] = [
  {
    "id": 292030,
    "slug": "the-witcher-3-wild-hunt",
    "title": "The Witcher 3: Wild Hunt",
    "tagline": "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.",
    "description": "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_5710298af2318afd9aa72449ef29ac4a2ef64d8e.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_0901e64e9d4b8ebaea8348c194e7a3644d2d832d.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_112b1e176c1bd271d8a565eacb6feaf90f240bb2.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_d1b73b18cbcd5e9e412c7a1dead3c5cd7303d2ad.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_107600c1337accc09104f7a8aa7f275f23cad096.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_64eb760f9a2b67f6731a71cce3a8fb684b9af267.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256927229/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256927229/movie.293x165.jpg"
    },
    "released": "May 18, 2015",
    "developers": [
      "CD PROJEKT RED"
    ],
    "publishers": [
      "CD PROJEKT RED"
    ],
    "genres": [
      "RPG"
    ],
    "tags": [
      "Open World",
      "Story Rich",
      "Fantasy"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch"
    ],
    "rating": 4.7,
    "ratingsCount": 42770,
    "metacritic": 93,
    "price": 39.99,
    "discount": 70,
    "featured": true,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "64-bit Windows 7, 64-bit Windows 8 (8.1)"
        },
        {
          "label": "Processor",
          "value": "Intel CPU Core i5-2500K 3.3GHz / AMD A10-5800K APU (3.8GHz)"
        },
        {
          "label": "Memory",
          "value": "6 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GPU GeForce GTX 660 / AMD GPU Radeon HD 7870"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "50 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "64-bit Windows 10/11"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-7400 / Ryzen 5 1600"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GTX 1070 / Radeon RX 480"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "50 GB available space"
        }
      ]
    }
  },
  {
    "id": 1091500,
    "slug": "cyberpunk-2077",
    "title": "Cyberpunk 2077",
    "tagline": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and…",
    "description": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_2f649b68d579bf87011487d29bc4ccbfdd97d34f.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_0e64170751e1ae20ff8fdb7001a8892fd48260e7.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_af2804aa4bf35d4251043744412ce3b359a125ef.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_7924f64b6e5d586a80418c9896a1c92881a7905b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_4eb068b1cf52c91b57157b84bed18a186ed7714b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_b529b0abc43f55fc23fe8058eddb6e37c9629a6a.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/257082775/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/257082775/885331d24a8e88a0a90903f588835ed38b2f82cf/movie_600x337.jpg"
    },
    "released": "Dec 9, 2020",
    "developers": [
      "CD PROJEKT RED"
    ],
    "publishers": [
      "CD PROJEKT RED"
    ],
    "genres": [
      "RPG"
    ],
    "tags": [
      "Cyberpunk",
      "Open World",
      "Shooter"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "macOS"
    ],
    "rating": 4.3,
    "ratingsCount": 37700,
    "metacritic": 86,
    "price": 59.99,
    "discount": 50,
    "featured": true,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "64-bit Windows 10"
        },
        {
          "label": "Processor",
          "value": "Core i7-6700 or Ryzen 5 1600"
        },
        {
          "label": "Memory",
          "value": "12 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "GeForce GTX 1060 6GB or Radeon RX 580 8GB or Arc A380"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "70 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "64-bit Windows 10"
        },
        {
          "label": "Processor",
          "value": "Core i7-12700 or Ryzen 7 7800X3D"
        },
        {
          "label": "Memory",
          "value": "16 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "GeForce RTX 2060 SUPER or Radeon RX 5700 XT or Arc A770"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "70 GB available space"
        }
      ]
    }
  },
  {
    "id": 1245620,
    "slug": "elden-ring",
    "title": "ELDEN RING",
    "tagline": "THE CRITICALLY ACCLAIMED FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord…",
    "description": "THE CRITICALLY ACCLAIMED FANTASY ACTION RPG Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.• A Breathtaking World Full of Excitement and Mystery The Lands Between are part of a vast continent where magnificent open fields and huge dungeons with complex and three-dimensional designs are seamlessly connected. As you explore, the joy of discovering unknown and overwhelming threats awaits you. Mastery of the terrain and knowledge of its secrets can help you overcome enemies and defeat formidable bosses or lead invading players into traps. • Defeat Challenging Foes in Intense Combat Combat in ELDEN RING is simple to learn yet offers hidden depths of mastery.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_943bf6fe62352757d9070c1d33e50b92fe8539f1.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_dcdac9e4b26ac0ee5248bfd2967d764fd00cdb42.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_3c41384a24d86dddd58a8f61db77f9dc0bfda8b5.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_e0316c76f8197405c1312d072b84331dd735d60b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_ef61b771ee6b269b1f0cb484233e07a0bfb5f81b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_b1b91299d7e4b94201ac840aa64de54d9f5cb7f3.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256889452/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256889452/movie.293x165.jpg"
    },
    "released": "Feb 24, 2022",
    "developers": [
      "FromSoftware, Inc."
    ],
    "publishers": [
      "FromSoftware, Inc.",
      "Bandai Namco Entertainment"
    ],
    "genres": [
      "Action",
      "RPG"
    ],
    "tags": [
      "Souls-like",
      "Difficult",
      "Open World"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X"
    ],
    "rating": 4.7,
    "ratingsCount": 17980,
    "metacritic": 94,
    "price": 59.99,
    "discount": 30,
    "featured": true,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10"
        },
        {
          "label": "Processor",
          "value": "INTEL CORE I5-8400 or AMD RYZEN 3 3300X"
        },
        {
          "label": "Memory",
          "value": "12 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GEFORCE GTX 1060 3 GB or AMD RADEON RX 580 4 GB"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "60 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10/11"
        },
        {
          "label": "Processor",
          "value": "INTEL CORE I7-8700K or AMD RYZEN 5 3600X"
        },
        {
          "label": "Memory",
          "value": "16 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GEFORCE GTX 1070 8 GB or AMD RADEON RX VEGA 56 8 GB"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "60 GB available space"
        }
      ]
    }
  },
  {
    "id": 1174180,
    "slug": "red-dead-redemption-2",
    "title": "Red Dead Redemption 2",
    "tagline": "Arthur Morgan and the Van der Linde Gang are outlaws on the run. With federal agents and bounty hunters massing on their heels, the gang must rob,…",
    "description": "America, 1899. Arthur Morgan and the Van der Linde Gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal, and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, Red Dead Redemption 2 is an epic tale of honor and loyalty at the dawn of the modern age. Red Dead Redemption 2 also includes Red Dead Online — the multiplayer experience set in the living world of Red Dead Redemption 2 — ride solo or form a posse; run moonshine; battle lawmen, outlaw gangs, ferocious wild animals, and much more as you forge your own path on the American frontier.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_66b553f4c209476d3e4ce25fa4714002cc914c4f.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_bac60bacbf5da8945103648c08d27d5e202444ca.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_668dafe477743f8b50b818d5bbfcec669e9ba93e.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_4ce07ae360b166f0f650e9a895a3b4b7bf15e34f.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_d1a8f5a69155c3186c65d1da90491fcfd43663d9.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256767979/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256767979/movie.293x165.jpg"
    },
    "released": "Dec 5, 2019",
    "developers": [
      "Rockstar Games"
    ],
    "publishers": [
      "Rockstar Games"
    ],
    "genres": [
      "Action",
      "Adventure"
    ],
    "tags": [
      "Western",
      "Open World",
      "Story Rich"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X"
    ],
    "rating": 4.7,
    "ratingsCount": 12620,
    "metacritic": 93,
    "price": 59.99,
    "discount": 67,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10 - 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel® Core™ i5-2500K / AMD FX-6300"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GeForce GTX 770 2GB / AMD Radeon R9 280 3GB"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        },
        {
          "label": "Storage",
          "value": "150 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10 - 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel® Core™ i7-4770K / AMD Ryzen 5 1500X"
        },
        {
          "label": "Memory",
          "value": "12 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        },
        {
          "label": "Storage",
          "value": "150 GB available space"
        }
      ]
    }
  },
  {
    "id": 1086940,
    "slug": "baldurs-gate-3",
    "title": "Baldur's Gate 3",
    "tagline": "Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and…",
    "description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Mysterious abilities are awakening inside you, drawn from a mind flayer parasite planted in your brain. Resist, and turn darkness against itself. Or embrace corruption, and become ultimate evil. From the creators of Divinity: Original Sin 2 comes a next-generation RPG, set in the world of Dungeons & Dragons. Choose from 12 classes and 11 races from the D&D Player's Handbook and create your own identity, or play as an Origin hero with a hand-crafted background. Or tangle with your inner corruption as the Dark Urge, a fully customisable Origin hero with its own unique mechanics and story. Whoever you choose to be, adventure, loot, battle and romance your way across the Forgotten Realms and beyond. Gather your party.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_c73bc54415178c07fef85f54ee26621728c77504.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_73d93bea842b93914d966622104dcb8c0f42972b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_cf936d31061b58e98e0c646aee00e6030c410cda.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_b6a6ee6e046426d08ceea7a4506a1b5f44181543.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_6b8faba0f6831a406ce015648958da9612d14dbb.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_8fc5eba770b4a1639b31666908bdd2bbc1aa2ae4.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256987424/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256987424/movie.293x165.jpg"
    },
    "released": "Aug 3, 2023",
    "developers": [
      "Larian Studios"
    ],
    "publishers": [
      "Larian Studios"
    ],
    "genres": [
      "Adventure",
      "RPG",
      "Strategy"
    ],
    "tags": [
      "CRPG",
      "Turn-Based",
      "Co-op"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "macOS"
    ],
    "rating": 4.8,
    "ratingsCount": 23060,
    "metacritic": 96,
    "price": 59.99,
    "discount": 0,
    "featured": true,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel I5 4690 / AMD FX 8350 / Snapdragon X Elite"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GTX 970 / RX 480 / Intel Arc A380 / Qualcomm Adreno X1 (4GB+ of VRAM)"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "150 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel i7 8700K / AMD r5 3600"
        },
        {
          "label": "Memory",
          "value": "16 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia 2060 Super / RX 5700 XT / Intel Arc A580 (8GB+ of VRAM)"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "150 GB available space"
        }
      ]
    }
  },
  {
    "id": 1145360,
    "slug": "hades",
    "title": "Hades",
    "tagline": "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and…",
    "description": "Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre.BATTLE OUT OF HELL As the immortal Prince of the Underworld, you'll wield the powers and mythic weapons of Olympus to break free from the clutches of the god of the dead himself, while growing stronger and unraveling more of the story with each unique escape attempt.UNLEASH THE FURY OF OLYMPUS The Olympians have your back! Meet Zeus, Athena, Poseidon, and many more, and choose from their dozens of powerful Boons that enhance your abilities. There are thousands of viable character builds to discover as you go.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_c0fed447426b69981cf1721756acf75369801b31.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_8a9f0953e8a014bd3df2789c2835cb787cd3764d.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_68300459a8c3daacb2ec687adcdbf4442fcc4f47.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_bcb499a0dd001f4101823f99ec5094d2872ba6ee.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_8e07e477fa7ff2f88c8984bc89b9652a655da0e9.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_34e6660705cfe47d2b2f95189c37f7cb77f75ca6.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256801252/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256801252/movie.293x165.jpg"
    },
    "released": "Sep 17, 2020",
    "developers": [
      "Supergiant Games"
    ],
    "publishers": [
      "Supergiant Games"
    ],
    "genres": [
      "Action",
      "Indie",
      "RPG"
    ],
    "tags": [
      "Roguelike",
      "Action",
      "Mythology"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS"
    ],
    "rating": 4.7,
    "ratingsCount": 27040,
    "metacritic": 93,
    "price": 24.99,
    "discount": 55,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7 SP1"
        },
        {
          "label": "Processor",
          "value": "Dual Core 2.4 GHz"
        },
        {
          "label": "Memory",
          "value": "4 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "1GB VRAM / DirectX 10+ support"
        },
        {
          "label": "Storage",
          "value": "15 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 7 SP1"
        },
        {
          "label": "Processor",
          "value": "Dual Core 3.0 GHz+"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "2GB VRAM / DirectX 10+ support"
        },
        {
          "label": "Storage",
          "value": "20 GB available space"
        }
      ]
    }
  },
  {
    "id": 367520,
    "slug": "hollow-knight",
    "title": "Hollow Knight",
    "tagline": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes.",
    "description": "Godmaster - Take your place amongst the Gods. New Characters and Quest. New Boss Fights. Available Now! Lifeblood - A Kingdom Upgraded! New Boss. Upgraded Bosses. Tweaks and Refinements across the whole game. The Grimm Troupe - Light the Nightmare Lantern. Summon the Troupe. New Major Quest. New Boss Fights. New Charms. New Enemies. New Friends. Hidden Dreams - Mighty new foes emerge! New Boss fights. New Upgrades. New Music. Beneath the fading town of Dirtmouth sleeps an ancient, ruined kingdom. Many are drawn below the surface, searching for riches, or glory, or answers to old secrets. Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdom's heart.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_5384f9f8b96a0b9934b2bc35a4058376211636d2.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_d5b6edd94e77ba6db31c44d8a3c09d807ab27751.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_a81e4231cc8d55f58b51a4a938898af46503cae5.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_62e10cf506d461e11e050457b08aa0e2a1c078d0.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_bd76bd88bc5334ee56ae3d5f0d8dec4455e8e3b8.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_33a645903d6dd9beec39f272a3daf57174a6cc26.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256679401/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256679401/movie.293x165.jpg"
    },
    "released": "Feb 24, 2017",
    "developers": [
      "Team Cherry"
    ],
    "publishers": [
      "Team Cherry"
    ],
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "tags": [
      "Metroidvania",
      "Difficult",
      "Atmospheric"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS",
      "Linux"
    ],
    "rating": 4.4,
    "ratingsCount": 8080,
    "metacritic": 87,
    "price": 14.99,
    "discount": 40,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10 version 21H1 (build 19043) or newer"
        },
        {
          "label": "Processor",
          "value": "Intel Core i3-3240, AMD FX-4300"
        },
        {
          "label": "Memory",
          "value": "4 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "GeForce GTX 560 Ti (1GB), Radeon HD 7750 (1GB)"
        },
        {
          "label": "DirectX",
          "value": "Version 10"
        },
        {
          "label": "Storage",
          "value": "9 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10 version 21H1 (build 19043) or newer"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-3470"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "GeForce GTX 1050 (2GB), Radeon R9 380 (2GB)"
        },
        {
          "label": "DirectX",
          "value": "Version 10"
        },
        {
          "label": "Storage",
          "value": "9 GB available space"
        }
      ]
    }
  },
  {
    "id": 413150,
    "slug": "stardew-valley",
    "title": "Stardew Valley",
    "tagline": "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new…",
    "description": "Stardew Valley is an open-ended country-life RPG! You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won't be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. The community center, once the town's most vibrant hub of activity, now lies in shambles. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness! • Turn your overgrown field into a lively farm!   Raise animals, grow crops, start an orchard, craft useful machines, and more! You'll have plenty of space to create the farm of your dreams.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_b887651a93b0525739049eb4194f633de2df75be.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_9ac899fe2cda15d48b0549bba77ef8c4a090a71c.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_4fa0866709ede3753fdf2745349b528d5e8c4054.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_d836f0a5b0447fb6a2bdb0a6ac5f954949d3c41e.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_10628b4a811c0a925a1433d4323f78c7017dbbe4.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_6422d297347258086b389e3d5d9c0e0c698312e4.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256815967/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256815967/movie.293x165.jpg"
    },
    "released": "Feb 26, 2016",
    "developers": [
      "ConcernedApe"
    ],
    "publishers": [
      "ConcernedApe"
    ],
    "genres": [
      "Indie",
      "RPG",
      "Simulation"
    ],
    "tags": [
      "Farming Sim",
      "Pixel Graphics",
      "Relaxing"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS",
      "Linux"
    ],
    "rating": 4.5,
    "ratingsCount": 8050,
    "metacritic": 89,
    "price": 14.99,
    "discount": 0,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows Vista or greater"
        },
        {
          "label": "Processor",
          "value": "2 Ghz"
        },
        {
          "label": "Memory",
          "value": "2 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "256 mb video memory, shader model 3.0+"
        },
        {
          "label": "DirectX",
          "value": "Version 10"
        },
        {
          "label": "Storage",
          "value": "500 MB available space"
        }
      ],
      "recommended": []
    }
  },
  {
    "id": 620,
    "slug": "portal-2",
    "title": "Portal 2",
    "tagline": "The \"Perpetual Testing Initiative\" has been expanded to allow you to design co-op puzzles for you and your friends!",
    "description": "Portal 2 draws from the award-winning formula of innovative gameplay, story, and music that earned the original Portal over 70 industry accolades and created a cult following. The single-player portion of Portal 2 introduces a cast of dynamic new characters, a host of fresh puzzle elements, and a much larger set of devious test chambers. Players will explore never-before-seen areas of the Aperture Science Labs and be reunited with GLaDOS, the occasionally murderous computer companion who guided them through the original game. The game’s two-player cooperative mode features its own entirely separate campaign with a unique story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew about portals. Success will require them to not just act cooperatively, but to think cooperatively.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_f3f6787d74739d3b2ec8a484b5c994b3d31ef325.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_6a4f5afdaa98402de9cf0b59fed27bab3256a6f4.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_0cdd90fafc160b52d08b303d205f9fd4e83cf164.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_ec35a739b4b33270eb170d9e561c5b016cba50a6.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_3d13161104a04603a0524536770c5f74626db4c0.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/ss_8a772608d29ffd56ac013d2ac7c4388b96e87a21.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/5787/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/5787/movie.293x165.jpg"
    },
    "released": "Apr 18, 2011",
    "developers": [
      "Valve"
    ],
    "publishers": [
      "Valve"
    ],
    "genres": [
      "Action",
      "Adventure"
    ],
    "tags": [
      "Puzzle",
      "Co-op",
      "Comedy"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Linux"
    ],
    "rating": 4.8,
    "ratingsCount": 14980,
    "metacritic": 95,
    "price": 9.99,
    "discount": 80,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7 / Vista / XP"
        },
        {
          "label": "Processor",
          "value": "3.0 GHz P4, Dual Core 2.0 (or higher) or AMD64X2 (or higher)"
        },
        {
          "label": "Memory",
          "value": "2 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Video card must be 128 MB or more and with support for Pixel Shader 2.0b (ATI Radeon X800 or higher / NVIDIA GeForce 7600 or higher / Intel HD Graphics 2000 or higher)."
        },
        {
          "label": "DirectX",
          "value": "Version 9.0c"
        },
        {
          "label": "Storage",
          "value": "8 GB available space"
        }
      ],
      "recommended": []
    }
  },
  {
    "id": 814380,
    "slug": "sekiro-shadows-die-twice",
    "title": "Sekiro™: Shadows Die Twice - GOTY Edition",
    "tagline": "Game of the Year - The Game Awards 2019 Best Action Game of 2019 - IGN Carve your own clever path to vengeance in the award winning adventure from…",
    "description": "This Game of the Year Edition now includes bonus content*: - Reflection and Gauntlet of Strength - new boss challenge modes - Remnants - leave messages and recordings of your actions that other players can view and rate Carve your own clever path to vengeance in the critically acclaimed adventure from developer FromSoftware, creators of the Dark Souls series. In Sekiro™: Shadows Die Twice you are the 'one-armed wolf', a disgraced and disfigured warrior rescued from the brink of death. Bound to protect a young lord who is the descendant of an ancient bloodline, you become the target of many vicious enemies, including the dangerous Ashina clan. When the young lord is captured, nothing will stop you on a perilous quest to regain your honor, not even death itself.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/ss_0f7b0f8ed9ffc49aba26f9328caa9a1d59ad60f0.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/ss_2685dd844a2a523b6c7ec207d46a538db6a908cd.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/ss_15f0e9982621aed44900215ad283811af0779b1d.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/ss_1e6f5540866a5564d65df915c22fe1e57e336a6f.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/ss_3d6b38c382c0eafb02dc90d22f33fd292e4e5cf3.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256806899/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256806899/movie.293x165.jpg"
    },
    "released": "Mar 21, 2019",
    "developers": [
      "FromSoftware, Inc."
    ],
    "publishers": [
      "Activision (Excluding Japan and Asia)",
      "FromSoftware, Inc. (Japan)",
      "方块游戏 (Asia)"
    ],
    "genres": [
      "Action",
      "Adventure"
    ],
    "tags": [
      "Souls-like",
      "Ninja",
      "Difficult"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X"
    ],
    "rating": 4.4,
    "ratingsCount": 36420,
    "metacritic": 88,
    "price": 59.99,
    "discount": 45,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7 64-bit | Windows 8 64-bit | Windows 10 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel Core i3-2100 | AMD FX-6300"
        },
        {
          "label": "Memory",
          "value": "4 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 760 | AMD Radeon HD 7950"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 7 64-bit | Windows 8 64-bit | Windows 10 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-2500K | AMD Ryzen 5 1400"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 970 | AMD Radeon RX 570"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        }
      ]
    }
  },
  {
    "id": 782330,
    "slug": "doom-eternal",
    "title": "DOOM Eternal",
    "tagline": "Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final…",
    "description": "Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity.The Only Thing they Fear... Is You. Experience the ultimate combination of speed and power in DOOM Eternal - the next leap in push-forward, first-person combat.Slayer Threat Level At Maximum Armed with a shoulder-mounted flamethrower, retractable wrist-mounted blade, upgraded guns and mods, and abilities, you're faster, stronger, and more versatile than ever.Unholy Trinity Take what you need from your enemies: Glory kill for extra health, incinerate for armor, and chainsaw demons to stock up on ammo to become the ultimate demon-slayer.Enter Battlemode A new 2 versus 1 multiplayer experience.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_4f93a7c5003d49cb32f6c0c6e547452b284580a0.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_7e6a2148321c8024285e3924903d8897cac95358.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_af3b43c4be0029b52ceefaf55ebe1918e2cb3471.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_ebd31ded4723e991446ededa9e65c980f988567d.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_c836f889d696fa2b81d5fe9f20f75dd925c1b499.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/ss_1fcebe3689c6a941257509a2ac4b2fdfb1344730.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/257182101/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/257182101/842d4f0e002d40b68833ca2db0137044ba1c04bc/movie_600x337.jpg"
    },
    "released": "Mar 19, 2020",
    "developers": [
      "id Software"
    ],
    "publishers": [
      "Bethesda Softworks"
    ],
    "genres": [
      "Action"
    ],
    "tags": [
      "FPS",
      "Gore",
      "Fast-Paced"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch"
    ],
    "rating": 4.4,
    "ratingsCount": 8470,
    "metacritic": 88,
    "price": 29.99,
    "discount": 75,
    "featured": true,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "64-bit Windows 7 / 64-Bit Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5 @ 3.3 GHz or better, or AMD Ryzen 3 @ 3.1 GHz or better"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 1050Ti (4GB), GTX 1060 (3GB), GTX 1650 (4GB) or AMD Radeon R9 280(3GB), AMD Radeon R9 290 (4GB), RX 470 (4GB)"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        },
        {
          "label": "Storage",
          "value": "80 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "64-bit Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel Core i7-6700K or better, or AMD Ryzen 7 1800X or better"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 1060 (6GB), NVIDIA GeForce 970 (4GB), AMD RX 480 (8GB)"
        },
        {
          "label": "Network",
          "value": "Broadband Internet connection"
        },
        {
          "label": "Storage",
          "value": "80 GB available space"
        }
      ]
    }
  },
  {
    "id": 1593500,
    "slug": "god-of-war",
    "title": "God of War",
    "tagline": "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters.",
    "description": "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same. Kratos is a father again. As mentor and protector to Atreus, a son determined to earn his respect, he is forced to deal with and control the rage that has long defined him while out in a very dangerous world with his son. Journey to a dark, elemental world of fearsome creatures From the marble and columns of ornate Olympus to the gritty forests, mountains and caves of pre-Viking Norse lore, this is a distinctly new realm with its own pantheon of creatures, monsters and gods.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_6eccc970b5de2943546d93d319be1b5c0618f21b.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_f1bff24d3967a21d303d95e11ed892e3d9113057.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_3670ba72c7e3e9c3c3225547ef2c1053504e62b8.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_93a3ca63aa2cd8c675bbb6430324ee3f2d44b845.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_1bd99270dcbd4ff9fe9c94b0d9c8ffc50ebb42c7.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_0858b868ea51d53f73bd805ba7382f027dd33dca.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256864004/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256864004/movie.293x165.jpg"
    },
    "released": "Jan 14, 2022",
    "developers": [
      "Santa Monica Studio",
      "Jetpack Interactive"
    ],
    "publishers": [
      "PlayStation Publishing LLC"
    ],
    "genres": [
      "Action",
      "Adventure",
      "RPG"
    ],
    "tags": [
      "Action",
      "Mythology",
      "Story Rich"
    ],
    "platforms": [
      "PC",
      "PlayStation 5"
    ],
    "rating": 4.7,
    "ratingsCount": 15700,
    "metacritic": 93,
    "price": 49.99,
    "discount": 35,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel i5-2500k (4 core 3.3 GHz) or AMD Ryzen 3 1200 (4 core 3.1 GHz)"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GTX 960 (4 GB) or AMD R9 290X (4 GB)"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "70 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel i5-6600k (4 core 3.5 GHz) or AMD Ryzen 5 2400 G (4 core 3.6 GHz)"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GTX 1060 (6 GB) or AMD RX 570 (4 GB)"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "70 GB available space"
        }
      ]
    }
  },
  {
    "id": 632470,
    "slug": "disco-elysium",
    "title": "Disco Elysium - The Final Cut",
    "tagline": "Disco Elysium - The Final Cut is a groundbreaking role playing game. You’re a detective with a unique skill system at your disposal and a whole city…",
    "description": "Disco Elysium - The Final Cut is the definitive edition of the groundbreaking role playing game.  You’re a detective with a unique skill system at your disposal and a whole city block to carve your path across. Interrogate unforgettable characters, crack murders, or take bribes. Become a hero or an absolute disaster of a human being. Full voice acting. All of the city's beautiful people are brought to life with full English voiceover. Play characters against each other, try to help them, or fall hopelessly in love as each word is spoken to you with the appropriate accent and emotion. New political vision quests. Face the reality of your worldview as your political compass leads you down new paths. Discover more citizens, a whole extra area, and monumental sights as you leave an even bigger mark on the world by chasing your dreams. Unprecedented freedom of choice​.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_b3694e99ffdb686d1bbbbe16a540d3d2ccd509c4.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_9125a718ee9ba85386ae5d4eb820f3266073fc97.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_4f5fdc3cf42feca8dafb1f7d2910ef96e62708a2.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_fc6969799ebf19fd2a2c8a986c9419e053606a17.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_dec29c440fab2f7817d68c1380c019290eb1755e.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632470/ss_ab38615b3a1d0d4309f06772db4bd9db5c250ef7.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256827872/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256827872/movie.293x165.jpg"
    },
    "released": "Oct 15, 2019",
    "developers": [
      "ZA/UM"
    ],
    "publishers": [
      "ZA/UM"
    ],
    "genres": [
      "RPG"
    ],
    "tags": [
      "Detective",
      "Dialogue",
      "Isometric"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS"
    ],
    "rating": 4.9,
    "ratingsCount": 19130,
    "metacritic": 97,
    "price": 39.99,
    "discount": 60,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7"
        },
        {
          "label": "Processor",
          "value": "Intel Core 2 Duo"
        },
        {
          "label": "Memory",
          "value": "2 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "DirectX 11 compatible video card (integrated or dedicated with min 512MB memory)"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "20 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 7/8/10"
        },
        {
          "label": "Processor",
          "value": "Intel Core i7 or AMD 1800 equivalent"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA Geforce 1060 or equivalent"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "20 GB available space"
        }
      ]
    }
  },
  {
    "id": 870780,
    "slug": "control",
    "title": "CONTROL Ultimate Edition",
    "tagline": "Winner of over 80 awards, CONTROL is a visually stunning third-person action-adventure that will keep you on the edge of your seat.",
    "description": "CONTROL Ultimate Edition contains the main game and all previously released Expansions (\"The Foundation\" and \"AWE\") in one great value package. A corruptive presence has invaded the Federal Bureau of Control…Only you have the power to stop it. The world is now your weapon in an epic fight to annihilate an ominous enemy through deep and unpredictable environments. Containment has failed, humanity is at stake. Will you regain control? Winner of over 80 awards, CONTROL is a visually stunning third-person action-adventure that will keep you on the edge of your seat. Blending open-ended environments with the signature world-building and storytelling of renowned developer, Remedy Entertainment, CONTROL presents an expansive and intensely gratifying gameplay experience.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_8376498631b089e52fb5c75ffe119e0de5e6aed1.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_5a16ce565951479e142c56a23f19d88333d84945.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_c038bb7b20d72ba5d33cc95f7235aefa0b84a706.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_949cf39deee737fec3aadff903ec5311dd22bdab.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_455ab81ea90f5668ff384d60d68baef1e2e74e55.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870780/ss_165fb4ca28f4db79b878e8c56ba6502e782c0bb2.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256795524/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256795524/movie.293x165.jpg"
    },
    "released": "Aug 27, 2020",
    "developers": [
      "Remedy Entertainment"
    ],
    "publishers": [
      "Remedy Entertainment"
    ],
    "genres": [
      "Action",
      "Adventure"
    ],
    "tags": [
      "Supernatural",
      "Third Person",
      "Atmospheric"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "macOS"
    ],
    "rating": 4.3,
    "ratingsCount": 28020,
    "metacritic": 85,
    "price": 39.99,
    "discount": 65,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7, 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-4690 / AMD FX 4350"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 780 / AMD Radeon R9 280X"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "42 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10, 64-bit"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-7600K / AMD Ryzen 5 1600X"
        },
        {
          "label": "Memory",
          "value": "16 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 1660/1060 / AMD Radeon RX 580 AMD | For Ray Tracing: GeForce RTX 2060"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "42 GB available space"
        }
      ]
    }
  },
  {
    "id": 504230,
    "slug": "celeste",
    "title": "Celeste",
    "tagline": "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall.",
    "description": "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight, hand-crafted platformer from the creators of multiplayer classic TowerFall. • A narrative-driven, single-player adventure like mom used to make, with a charming cast of characters and a touching story of self-discovery • A massive mountain teeming with 700+ screens of hardcore platforming challenges and devious secrets • Brutal B-side chapters to unlock, built for only the bravest mountaineers • IGF “Excellence in Audio” finalist, with over 2 hours of original music led by dazzling live piano and catchy synth beats The controls are simple and accessible - simply jump, air-dash, and climb - but with layers of expressive depth to master, where every death is a lesson. Lightning-fast respawns keep you climbing as you uncover the mysteries of the mountain and brave its many perils.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_1ad297c2044cdcf450ee83e56350cafb590da755.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_03bfe6bd5ddac7f747c8d2aa1a4f82cfd53c6dcb.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_4b0f0222341b64a37114033aca9994551f27c161.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_1012b11ad364ad6c138a25a654108de28de56c5f.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_832ef0f27c3d6efdaa4b5d1cc896dce0999bc9e8.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/ss_1098b655a622720cfd549b104736a4eca8948100.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256706951/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256706951/movie.293x165.jpg"
    },
    "released": "Jan 25, 2018",
    "developers": [
      "Maddy Makes Games Inc.",
      "Extremely OK Games, Ltd."
    ],
    "publishers": [
      "Maddy Makes Games Inc."
    ],
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "tags": [
      "Platformer",
      "Pixel Graphics",
      "Difficult"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS",
      "Linux"
    ],
    "rating": 4.4,
    "ratingsCount": 22570,
    "metacritic": 88,
    "price": 19.99,
    "discount": 0,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7 or newer"
        },
        {
          "label": "Processor",
          "value": "Intel Core i3 M380"
        },
        {
          "label": "Memory",
          "value": "2 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Intel HD 4000"
        },
        {
          "label": "DirectX",
          "value": "Version 10"
        },
        {
          "label": "Storage",
          "value": "1200 MB available space"
        }
      ],
      "recommended": []
    }
  },
  {
    "id": 268910,
    "slug": "cuphead",
    "title": "Cuphead",
    "tagline": "Cuphead is a classic run and gun action game heavily focused on boss battles.",
    "description": "Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era, i.e. traditional hand drawn cel animation, watercolor backgrounds, and original jazz recordings. Play as Cuphead or Mugman (in single player or local co-op) as you traverse strange worlds, acquire new weapons, learn powerful super moves, and discover hidden secrets while you try to pay your debt back to the devil!",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_e3096a5555cb77d88db165c83d5ef3a24af1354a.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_615455299355eaf552c638c7ea5b24a8b46e02dd.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_483fb089be0093beeef03525276803a9ca4f66a1.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_48477e4a865827aa0be6a44f00944d8d2a3e5eb9.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_380296effbf1073bbedfd480e50cf246eb542b66.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/ss_aefad3850c3bc04000cbe0d620bea6807e0a0331.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256894191/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256894191/movie.293x165.jpg"
    },
    "released": "Sep 29, 2017",
    "developers": [
      "Studio MDHR Entertainment Inc."
    ],
    "publishers": [
      "Studio MDHR Entertainment Inc."
    ],
    "genres": [
      "Action",
      "Indie"
    ],
    "tags": [
      "Run and Gun",
      "Hand-drawn",
      "Difficult"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS"
    ],
    "rating": 4.4,
    "ratingsCount": 27490,
    "metacritic": 88,
    "price": 19.99,
    "discount": 30,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 7"
        },
        {
          "label": "Processor",
          "value": "Intel Core2 Duo E8400, 3.0GHz or AMD Athlon 64 X2 6000+, 3.0GHz or higher"
        },
        {
          "label": "Memory",
          "value": "3 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Geforce 9600 GT or AMD HD 3870 512MB or higher"
        },
        {
          "label": "DirectX",
          "value": "Version 11"
        },
        {
          "label": "Storage",
          "value": "4 GB available space"
        }
      ],
      "recommended": []
    }
  },
  {
    "id": 1332010,
    "slug": "stray",
    "title": "Stray",
    "tagline": "Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten cybercity and find their way home.",
    "description": "Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city. Stray is a third-person cat adventure game set amidst the detailed, neon-lit alleys of a decaying cybercity and the murky environments of its seedy underbelly. Roam surroundings high and low, defend against unforeseen threats and solve the mysteries of this unwelcoming place inhabited by curious droids and dangerous creatures. See the world through the eyes of a cat and interact with the environment in playful ways. Be stealthy, nimble, silly, and sometimes as annoying as possible with the strange inhabitants of this mysterious world. Along the way, the cat befriends a small flying drone, known only as B-12. With the help of this newfound companion, the duo must find a way out.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/1332010/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/1332010/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/1332010/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_88e209a90c2039fa76bca6fa08c641365be38d50.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_e8f0cbd5efdba352e89c4cfcee3fe991a1e1be8a.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_2221af260c64362fdc835a9dca65f6f1d1192b25.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_3fdd04a5418293864bf82d33c75f833121e63804.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_90f8a99d0d1454bc77f46542f00f9ae5043c4268.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/ss_a697971e484b3deef50153a13f2afd0539347d23.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/256896952/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256896952/movie.293x165.jpg"
    },
    "released": "Jul 19, 2022",
    "developers": [
      "BlueTwelve Studio"
    ],
    "publishers": [
      "Annapurna Interactive"
    ],
    "genres": [
      "Adventure",
      "Indie"
    ],
    "tags": [
      "Cats",
      "Adventure",
      "Cyberpunk"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "macOS"
    ],
    "rating": 4.1,
    "ratingsCount": 44390,
    "metacritic": 82,
    "price": 29.99,
    "discount": 50,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-2300 | AMD FX-6350"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 650 Ti, 2 GB | AMD Radeon R7 360, 2 GB"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "10 GB available space"
        }
      ],
      "recommended": [
        {
          "label": "OS",
          "value": "Windows 10"
        },
        {
          "label": "Processor",
          "value": "Intel Core i5-8400 | AMD Ryzen 5 2600"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "NVIDIA GeForce GTX 780, 3 GB | AMD Radeon R9 290X, 4 GB"
        },
        {
          "label": "DirectX",
          "value": "Version 12"
        },
        {
          "label": "Storage",
          "value": "10 GB available space"
        }
      ]
    }
  },
  {
    "id": 275850,
    "slug": "no-mans-sky",
    "title": "No Man's Sky",
    "tagline": "No Man's Sky is a game about exploration and survival in an infinite procedurally generated universe.",
    "description": "Inspired by the adventure and imagination that we love from classic science-fiction, No Man's Sky presents you with a galaxy to explore, filled with unique planets and lifeforms, and constant danger and action. In No Man's Sky, every star is the light of a distant sun, each orbited by planets filled with life, and you can go to any of them you choose. Fly smoothly from deep space to planetary surfaces, with no loading screens, and no limits. In this infinite procedurally generated universe, you'll discover places and creatures that no other players have seen before - and perhaps never will again.",
    "cover": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/library_600x900.jpg",
    "hero": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/library_hero.jpg",
    "capsule": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/capsule_616x353.jpg",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/461fd47ac75ae169f274f0c8b222ad77fbc45ce7/ss_461fd47ac75ae169f274f0c8b222ad77fbc45ce7.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/71f533720e58e1fb5dd61f23388abfe4f9caa6b5/ss_71f533720e58e1fb5dd61f23388abfe4f9caa6b5.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/6db1fa75dba6d47fa8484c1565fc544023c300d0/ss_6db1fa75dba6d47fa8484c1565fc544023c300d0.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/251992eb497ebef3bbd6e81e2c3e80a00d2770a6/ss_251992eb497ebef3bbd6e81e2c3e80a00d2770a6.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/d8de91e4a87f0e2c0fb70c84bd0f798bd4617eaf/ss_d8de91e4a87f0e2c0fb70c84bd0f798bd4617eaf.1920x1080.jpg",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/1712db8fdd282cb1a4c87598148e0fbb9bc0b744/ss_1712db8fdd282cb1a4c87598148e0fbb9bc0b744.1920x1080.jpg"
    ],
    "trailer": {
      "src": "https://video.akamai.steamstatic.com/store_trailers/257395628/movie480.mp4",
      "poster": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/257395628/5e869dff3dcec0bbed1c4f5c9833bf412ea04554/movie_600x337.jpg"
    },
    "released": "Aug 12, 2016",
    "developers": [
      "Hello Games"
    ],
    "publishers": [
      "Hello Games"
    ],
    "genres": [
      "Action",
      "Adventure"
    ],
    "tags": [
      "Space",
      "Survival",
      "Exploration"
    ],
    "platforms": [
      "PC",
      "PlayStation 5",
      "Xbox Series X",
      "Nintendo Switch",
      "macOS"
    ],
    "rating": 3.1,
    "ratingsCount": 25350,
    "metacritic": 61,
    "price": 59.99,
    "discount": 60,
    "featured": false,
    "requirements": {
      "minimum": [
        {
          "label": "OS",
          "value": "Windows 10/11 (64-bit versions)"
        },
        {
          "label": "Processor",
          "value": "Intel Core i3"
        },
        {
          "label": "Memory",
          "value": "8 GB RAM"
        },
        {
          "label": "Graphics",
          "value": "Nvidia GTX 1060 3GB, AMD RX 470 4GB, Intel UHD graphics 630"
        },
        {
          "label": "Storage",
          "value": "15 GB available space"
        },
        {
          "label": "VR Support",
          "value": "SteamVR"
        }
      ],
      "recommended": []
    }
  }
]
